package com.hstudio.jcalendarview

enum class JCalendarLine {
    HEADER_LEFT, HEADER_TOP, HEADER_RIGHT, HEADER_BOTTOM, HEADER_SPLIT,
    BODY_LEFT, BODY_TOP, BODY_RIGHT, BODY_BOTTOM, BODY_SPLIT_HORIZONTAL, BODY_SPLIT_VERTICAL,
    FOCUS_BODY
}